databases:
  - name: postgresql
    plan: free
    databaseName: Chatbot
    user: postgres

services:
  - type: web
    plan: free
    name: Chatbot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Chatbot
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
