# Generated by Django 5.0.7 on 2024-08-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_unansweredquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='funny_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
