# Generated by Django 4.2.9 on 2024-08-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_questionanswer_funny_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='funny_answer',
        ),
        migrations.RemoveField(
            model_name='unansweredquestion',
            name='funny_answer',
        ),
    ]
