# Generated by Django 5.0.6 on 2024-05-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_questionanswer_delete_faq_delete_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
