# Generated by Django 5.0.6 on 2024-05-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_alter_questionanswer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
