# Generated by Django 5.0.6 on 2024-05-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_alter_questionanswer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionanswer',
            table=None,
        ),
    ]
